# This is a basic workflow to help you get started with Actions

name: CI_dev

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dev-punkwalker"]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Lint using shfmt
        run: docker run --rm -v $(pwd):/script mvdan/shfmt --list --language-dialect auto --indent 2 --binary-next-line --case-indent --space-redirects /script/eks-pod-information-collector.sh
      - name: Analyze using shellcheck
        run: docker run --rm -v $(pwd):/script koalaman/shellcheck:stable --format gcc --severity error /script/eks-pod-information-collector.sh
      - name: Build project
        run: |
          git diff-tree --check $(git hash-object -t tree /dev/null) HEAD
